"""
Safety & Compliance Guardrails
- Blocks specific buy/sell price advice
- Detects and redacts PII from outputs
- Adds confidence scoring and data-gap warnings
- Appends mandatory disclaimer
"""
import re
from loguru import logger


# Patterns that suggest specific actionable financial advice
ADVICE_PATTERNS = [
    r"\bbuy\s+at\b",
    r"\bsell\s+at\b",
    r"\btarget\s+price[\s:]+[\$₹£€]?\s*\d+",
    r"\bstop[\s-]?loss[\s:]+[\$₹£€]?\s*\d+",
    r"\bentry\s+point[\s:]+[\$₹£€]?\s*\d+",
    r"\byou\s+should\s+(buy|sell|invest|short)\b",
    r"\bi\s+recommend\s+(buying|selling|investing)\b",
    r"\bguaranteed\s+(return|profit|gain)\b",
]

# Simple PII patterns
PII_PATTERNS = [
    (r"\b\d{10,12}\b", "[PHONE_REDACTED]"),                    # phone numbers
    (r"\b[A-Z]{5}\d{4}[A-Z]\b", "[PAN_REDACTED]"),            # Indian PAN
    (r"\b\d{4}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}\b", "[CARD_REDACTED]"),  # card numbers
]

DISCLAIMER = (
    "\n\n---\n"
    "⚠️ **Disclaimer:** This analysis is generated by an AI system for informational and "
    "educational purposes only. It does not constitute financial advice, investment "
    "recommendations, or an offer to buy or sell any security. Always consult a SEBI-registered "
    "financial advisor before making investment decisions."
)


def check_for_advice(text: str) -> list[str]:
    """Return list of flagged pattern matches in text."""
    flags = []
    for pattern in ADVICE_PATTERNS:
        if re.search(pattern, text, re.IGNORECASE):
            flags.append(pattern)
    return flags


def redact_pii(text: str) -> str:
    """Redact known PII patterns from AI output."""
    for pattern, replacement in PII_PATTERNS:
        text = re.sub(pattern, replacement, text)
    return text


def compute_confidence(data: dict, news: list) -> float:
    """
    Compute a 0–1 confidence score based on data coverage.
    - Financial metrics available → +0.4
    - Company overview available → +0.2
    - News articles available    → +0.2 (up to 5 articles)
    - No errors in data          → +0.2
    """
    score = 0.0

    if data.get("price") and data["price"] > 0:
        score += 0.4
    if data.get("company_name"):
        score += 0.2
    if news:
        score += min(len(news) / 5, 1.0) * 0.2
    if "error" not in data:
        score += 0.2

    return round(min(score, 1.0), 2)


def apply_guardrails(text: str, add_disclaimer: bool = True) -> tuple[str, list[str]]:
    """
    Run all guardrails on an AI output string.
    Returns (sanitised_text, list_of_warnings).
    """
    warnings = []

    # 1. Check for specific financial advice
    flags = check_for_advice(text)
    if flags:
        logger.warning(f"[guardrails] financial advice detected: {flags}")
        warnings.append(
            "Response contained specific financial advice language and was sanitised."
        )
        # Replace problematic sentences with a generic note
        for pattern in flags:
            text = re.sub(
                pattern,
                "[specific financial advice removed]",
                text,
                flags=re.IGNORECASE,
            )

    # 2. Redact PII
    clean = redact_pii(text)
    if clean != text:
        warnings.append("PII detected and redacted from output.")
        text = clean

    # 3. Add disclaimer
    if add_disclaimer and DISCLAIMER not in text:
        text += DISCLAIMER

    return text, warnings